### ISSUE TITLE
No action on UI after clicking the button "DELETE DRAFT"

### ISSUE THREAD

**Issue by szymcio32** [DA0-DA0/docs#30]
No action on UI after clicking the button "DELETE DRAFT" on the proposal window.

![juno_dao-5](https://user-images.githubusercontent.com/32844693/151066142-bebbb6b5-2eff-49da-8520-0a987c619628.png)

**Comment by elsehow** [comment]
I can replicate this. Moving to the dao-ui repo (will be open sourced on Jan 31).
