### ISSUE TITLE
Unstaking tokens amount bug

### ISSUE THREAD

**Issue by szymcio32** [DA0-DA0/docs#31]
It's possible to request 01 amount of token for unstaking when I have 1 token staked

![3](https://user-images.githubusercontent.com/32844693/151254026-d0294bcf-6dcb-4f23-ba9f-7bfade92b65d.png)
.

**Comment by elsehow** [comment]
I think this is expected behavior. If you have 1 token staked, you should be able to unstake that 1 token.

Closing this for now. Feel free to re-open if I misunderstood.
