### ISSUE TITLE
Incorrect messages when rejecting the staking transaction

### ISSUE THREAD

**Issue by szymcio32** [DA0-DA0/docs#32]
An unsuccessful and successful message appears when rejecting the staking transaction in the wallet

![4](https://user-images.githubusercontent.com/32844693/151254590-78d107a1-20e9-4f54-905b-21a89d66948b.png)
![5](https://user-images.githubusercontent.com/32844693/151254599-366bd52a-62a9-41c8-a967-53ff791b2859.png)
.

**Comment by elsehow** [comment]
Fixed.
