### ISSUE TITLE
improve contributor onboarding process

### ISSUE THREAD

**Issue by blue-note** [DA0-DA0/docs#53]
a good meta-contribution: improving the process for new contributors to contribute. I think our contributor guidelines could use some sprucing up with more details under each of the categories under 'how to contribute': https://docs.daodao.zone/docs/how-to-contribute. for example, in dao-contracts there are several issues with the good-first-issue tag, we could link to those in the doc: https://github.com/DA0-DA0/dao-contracts/issues?q=is%3Aissue+is%3Aopen+label%3Agood-first-issue. Could also use a description of how to fork the repo and create a PR against it without needing to be added to the github repo. Also, I feel like i've noticed some non-technical folks wanting to contribute but being unsure how to. Maybe we could differentiate between technical / non-technical contributions in the guidelines, and add some more non-technical contribution examples such as user interviews or writing. after our guidelines are better we can pin them in some of the channels. the goal is to make it easier to bring more voices in from the periphery (and with us having a contribution-first culture, the process should be as streamlined as possible)

**Comment by CLHRAE** [comment]
I'd be happy to dig in here.  DAO DAO contributor UX is a super important thing.   Once organised, a whole contributor recruitment exercise could be a good focus (sorry, I have a habit of getting ahead of myself).  

Initial thought is having a channel in discord dedicated to new contributors.  #Start-here or equivalent.  Developing a self directed on boarding experience, can be as simple as directing to the upgraded how to contribute.  Also maybe having a point of contact for "want to be contributors" might be helpful.

**Comment by grubcowboy** [comment]
hey, i am working on adding first-issues and discord links to the Contributor Guideline, and adding a short statement for each type of contribution. waiting to hear back on Design onboarding process to add it to doc, and then will make PR.

I can also add non-technical contribution section, but am wondering if the items mentioned (interviews, etc.) will be changing, and if so, should they be explicitly added to this doc? could alternatively have it link to something that is updated, periodically, to reflect what DD needs at that time.

**Comment by blue-note** [comment]
thanks for your help on this! I think it would be great to include user interviews as part of this doc! that doesn't seem like a need that will go away anytime soon

**Comment by CLHRAE** [comment]
I totally dropped the ball on this one.  Forgive me.

Here is an idea for helping new discord users flow to the information they may be looking for.

#Start-Here or #Welcome channel on Discord.

Welcome to the DAO DAO discord.  We're glad you're here.

This is the space for you to start your DAO DAO journey.

What made you come to DAO DAO discord?

Interested in Contributing?  
[Start with "How to Contribute]( https://docs.daodao.zone/docs/how-to-contribute).

Want to build an awesome DAO?
[Start with "DAO DAO Docs"](https://docs.daodao.zone/)
[Move on to the DAO DAO wiki for more advanced topics][(](https://github.com/DA0-DA0/dao-contracts/wiki)

DAO Curious?
Have a read through the channels on the sidebar.  Dive in to any one that peeks your interest.


^^^ An initial idea to start the conversation.   What have I missed?  How do you think new discord users might benefit?

**Comment by CLHRAE** [comment]
Looks like an integrations bomb has gone off in discord.   

We should add: 
Want to integrate DAO DAO with your product?
visit #integrations channel.  or similar.

**Comment by CLHRAE** [comment]
https://docs.google.com/document/d/12WpREOPrvhW3YVxGLoOkrhTgf_bDUy4cn9VKeyH4PUY/edit

@elsehow put together the above document for how contributor compensation works.   A nice add for the contributor onboarding.

**Comment by elsehow** [comment]
I've updated the docs to link to this Google doc @CLHRAE mentions. (I acknowledge that the Google doc itself is highly imperfect, but it's easy to update as we work through the process). I will close this issue for now. Feel free to re-open it as needed, though I suspect some of these discussions should probably center more on the Discord than the docs.
